- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com

## When there is a variable reference(calling variable), Double quote it

- name: Demo on Inventory variables
  hosts: all
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"