- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com

## When there is a variable reference(calling variable), Double quote it

- name: Demo on Inventory variables
  hosts: all
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"

- name: Demo on File variables
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Print a Variable
      ansible.builtin.debug:
        msg: "URL = {{URL}}"

- name: Demo on Facts
  hosts: all
  tasks:
    - name: Print a Fact Variable
      ansible.builtin.debug:
        msg: "Hostname = {{ansible_hostname}}"

- name: Demo on Register Variables
  hosts: all
  tasks:
    - name: Run Uptime Command
      ansible.builtin.shell: uptime
      register: out

    - name: Set a Variable
      ansible.builtin.set_fact:
        UPTIME: "{{out.stdout}}"

    - name: Print output
      ansible.builtin.debug:
        msg: "{{UPTIME}}"

- name: Demo on Roles
  hosts: all
  roles:
    -name: demo