- name: Install Nodejs
  hosts: all
  become: yes
  ##Here all tasks run as root user
  tasks:
    - name: Install Nodejs
      become: yes
      ## This makes only this task to run as sudo
      ansible.builtin.yum:
        name: nodejs
        state: present