- name: Demo on Conditions
  hosts: localhost
  vars:
    URL: google.org
  tasks:
    - name: Condition on Strings
      when: URL == "google.com"
      debug:
        msg: Heloo

    - name: Condition on Strings
      when: URL ==! "google.com"
      debug:
        msg: World