- name: Demo on Conditions
  hosts: localhost
  vars:
    URL: google.org
    a: 10
    ACTION: false
  tasks:
    - name: Condition on Strings
      when: URL == "google.com"
      debug:
        msg: Heloo

    - name: Condition on Strings
      when: URL != "google.com"
      debug:
        msg: World

    - name: Condition on Numbers
      when: a == 10
      debug:
        msg: Number is 10

    - name: Condition on Numbers
      when: a <= 10
      debug:
        msg: Number is less than 10


    - name: Run If Action Is True
      when: ACTION
      debug:
        msg: Hello


    - name: Run If Action Is Not True
      when: not ACTION
      debug:
        msg: Hello


    - name: Run If Variable B is Declared
      when: B is defined
      debug:
        msg: Hello

    - name: Run If Variable B is Defined and less than 10
      when: B is not defined and a <= 10
      debug:
        msg: Hello