- name: Roboshop Frontend Setup
  hosts: FRONTEND
  become: yes
  roles:
    - name: frontend

- name: Roboshop MongoDb Setup
  hosts: frontend.mongodb.internal
  become: yes
  roles:
    - name: mongodb