- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download and Extract Frontend Content
  include_role:
    name: common
    tasks_from: download

- name: Copy the Extracted Content
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy the Roboshop Configuration File
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart Nginx Service
  systemd:
    name: nginx
    state: restarted
    enabled: yes








