- name: Add Roboshop Application User
  ansible.builtin.user:
    name: roboshop

- name: Download from GitHub
  include_tasks:
    file: download-from-github.yml


- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}
    status: absent

- name: Copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop