- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Download App Code & Add App User
  include_tasks:
    file: download.yml

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Update SystemD Configuration
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  notify: Restart Service - Handler

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes